/**
 * Regression suite for the two-layer plan-status durability gap.
 *
 * Layer 1 (in-memory): session.taskWorkflowStates Map. Mutated by
 *   advanceTaskState. Sync, fast, used by gate checks. Lost on restart.
 * Layer 2 (durable):   plan.json task.status, projected to plan.md via
 *   derivePlanMarkdown. Mutated by savePlan/updateTaskStatus.
 *
 * The bug was that the two layers had no bridge: advanceTaskState would
 * reach 'complete' on council APPROVE but plan.md stayed at [ ]. The fix
 * is advanceTaskStateAndPersist, which advances Layer 1 and persists the
 * meaningful workflow boundaries to Layer 2.
 *
 * What this file asserts:
 *   1. updateTaskStatus alone updates plan.json + plan.md (control).
 *   2. advanceTaskState alone is intentionally Layer-1-only (contract).
 *   3. advanceTaskStateAndPersist updates both layers (the fix).
 */

import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import {
	existsSync,
	mkdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import * as path from 'node:path';
import type { Plan } from '../src/config/plan-schema';
import { loadPlan, updateTaskStatus } from '../src/plan/manager';
import {
	advanceTaskState,
	advanceTaskStateAndPersist,
	resetSwarmState,
	startAgentSession,
	swarmState,
} from '../src/state';

const TEST_BASE_DIR = path.join(process.cwd(), '.test-repro-plan-md');
const SWARM_ID = 'repro-swarm';
const TASK_ID = '1.1';

function makePlan(): Plan {
	return {
		schema_version: '1.0.0',
		title: 'Repro Plan',
		swarm: SWARM_ID,
		migration_status: 'native',
		current_phase: 1,
		phases: [
			{
				id: 1,
				name: 'Phase 1',
				status: 'pending',
				tasks: [
					{
						id: TASK_ID,
						phase: 1,
						status: 'pending',
						size: 'small',
						description: 'Repro task — should advance to completed',
						depends: [],
						files_touched: [],
					},
				],
			},
		],
	};
}

function writePlanJson(dir: string, plan: Plan): void {
	const swarmDir = path.join(dir, '.swarm');
	mkdirSync(swarmDir, { recursive: true });
	writeFileSync(
		path.join(swarmDir, 'plan.json'),
		JSON.stringify(plan, null, 2),
		'utf-8',
	);
}

function readPlanJson(dir: string): Plan {
	const raw = readFileSync(path.join(dir, '.swarm', 'plan.json'), 'utf-8');
	return JSON.parse(raw) as Plan;
}

function cleanup() {
	if (existsSync(TEST_BASE_DIR)) {
		rmSync(TEST_BASE_DIR, { recursive: true, force: true });
	}
	// resetSwarmState also clears the module-level rehydration cache that other
	// state-related test files may have populated; agentSessions.clear() alone
	// is not sufficient under cross-file test runs.
	resetSwarmState();
}

beforeEach(() => {
	cleanup();
	mkdirSync(TEST_BASE_DIR, { recursive: true });
});

afterEach(() => {
	cleanup();
});

describe('Plan persistence — control test (updateTaskStatus directly)', () => {
	it('updateTaskStatus DOES persist completed status to plan.json', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		await updateTaskStatus(TEST_BASE_DIR, TASK_ID, 'completed');

		const plan = readPlanJson(TEST_BASE_DIR);
		const task = plan.phases[0].tasks[0];
		expect(task.status).toBe('completed');
	});

	it('updateTaskStatus DOES update plan.md checkbox to [x]', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		await updateTaskStatus(TEST_BASE_DIR, TASK_ID, 'completed');

		const mdPath = path.join(TEST_BASE_DIR, '.swarm', 'plan.md');
		// plan.md is regenerated by savePlan inside updateTaskStatus
		expect(existsSync(mdPath)).toBe(true);
		const md = readFileSync(mdPath, 'utf-8');
		// Markdown checklist for the completed task should use [x]
		expect(md).toMatch(/- \[x\][^\n]*1\.1/);
	});
});

describe('Plan persistence — Layer 1 contract (advanceTaskState is in-memory only)', () => {
	// These tests document an intentional contract: the sync state machine
	// MUST NOT touch disk. Persistence is the bridge helper's job.
	it('advanceTaskState alone advances Layer 1 but does not touch plan.json', () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		const sessionId = 'layer1-session-json';
		startAgentSession(sessionId, 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get(sessionId);
		if (!session) throw new Error('session not created');

		advanceTaskState(session, TASK_ID, 'coder_delegated');
		advanceTaskState(session, TASK_ID, 'pre_check_passed');
		advanceTaskState(session, TASK_ID, 'reviewer_run');
		advanceTaskState(session, TASK_ID, 'tests_run');
		advanceTaskState(session, TASK_ID, 'complete');

		expect(session.taskWorkflowStates.get(TASK_ID)).toBe('complete');

		// Layer 2 must be untouched by the sync state machine.
		const plan = readPlanJson(TEST_BASE_DIR);
		expect(plan.phases[0].tasks[0].status).toBe('pending');
	});
});

describe('Plan persistence — Layer 1↔2 bridge (advanceTaskStateAndPersist)', () => {
	it('coder_delegated advances Layer 1 AND marks task in_progress on disk', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		const sessionId = 'bridge-session-coder';
		startAgentSession(sessionId, 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get(sessionId);
		if (!session) throw new Error('session not created');

		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'coder_delegated',
			TEST_BASE_DIR,
		);

		expect(session.taskWorkflowStates.get(TASK_ID)).toBe('coder_delegated');

		const plan = readPlanJson(TEST_BASE_DIR);
		expect(plan.phases[0].tasks[0].status).toBe('in_progress');
	});

	it('complete advances Layer 1 AND marks task completed on disk + [x] in plan.md', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		const sessionId = 'bridge-session-complete';
		startAgentSession(sessionId, 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get(sessionId);
		if (!session) throw new Error('session not created');

		// Walk the state machine the full distance (intermediate states are
		// in-memory only — that's the contract).
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'coder_delegated',
			TEST_BASE_DIR,
		);
		advanceTaskState(session, TASK_ID, 'pre_check_passed');
		advanceTaskState(session, TASK_ID, 'reviewer_run');
		advanceTaskState(session, TASK_ID, 'tests_run');
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'complete',
			TEST_BASE_DIR,
		);

		expect(session.taskWorkflowStates.get(TASK_ID)).toBe('complete');

		const plan = readPlanJson(TEST_BASE_DIR);
		expect(plan.phases[0].tasks[0].status).toBe('completed');

		const mdPath = path.join(TEST_BASE_DIR, '.swarm', 'plan.md');
		expect(existsSync(mdPath)).toBe(true);
		const md = readFileSync(mdPath, 'utf-8');
		expect(md).toMatch(/- \[x\][^\n]*1\.1/);
	});

	it('intermediate states pass through advanceTaskStateAndPersist without disk writes', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		const sessionId = 'bridge-session-intermediate';
		startAgentSession(sessionId, 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get(sessionId);
		if (!session) throw new Error('session not created');

		// Bring it through coder_delegated so disk shows in_progress.
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'coder_delegated',
			TEST_BASE_DIR,
		);
		// Intermediate states via the helper must be a no-op on disk
		// (the task is already in_progress; only complete should re-write).
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'pre_check_passed',
			TEST_BASE_DIR,
		);
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'reviewer_run',
			TEST_BASE_DIR,
		);
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'tests_run',
			TEST_BASE_DIR,
		);

		const plan = readPlanJson(TEST_BASE_DIR);
		// Status remained in_progress through all intermediate transitions.
		expect(plan.phases[0].tasks[0].status).toBe('in_progress');
	});

	it('persistence error does not break the in-memory transition', async () => {
		// No plan.json on disk — updateTaskStatus will throw "Plan not found".
		// The bridge must swallow that and still advance Layer 1.
		const sessionId = 'bridge-session-resilient';
		startAgentSession(sessionId, 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get(sessionId);
		if (!session) throw new Error('session not created');

		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'coder_delegated',
			TEST_BASE_DIR,
		);

		expect(session.taskWorkflowStates.get(TASK_ID)).toBe('coder_delegated');
	});
});

describe('Plan persistence — sanity check (loadPlan after hand-crafted plan.json)', () => {
	it('loadPlan returns the plan we wrote', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());
		const plan = await loadPlan(TEST_BASE_DIR);
		expect(plan).not.toBeNull();
		expect(plan?.phases[0].tasks[0].id).toBe(TASK_ID);
		expect(plan?.phases[0].tasks[0].status).toBe('pending');
	});
});
