/**
 * Skill-improver service — produces a proposal markdown reviewing accumulated
 * knowledge, generated skills, the spec, and the architect prompt. When an
 * LLM delegate is available the body is generated by the configured
 * skill_improver agent (issue #629). When no delegate is wired and the
 * `allow_deterministic_fallback` flag is true, a deterministic offline body
 * is written, clearly tagged.
 *
 * Quota policy:
 *   - Reservation happens BEFORE any network I/O.
 *   - If the delegate is undefined and fallback is disabled, no quota is
 *     reserved — we refuse early with `no_llm_client`.
 *   - If the delegate construction itself fails before any network call
 *     (extremely unlikely in practice), we release the quota.
 *   - Once `client.session.prompt` has begun, the slot stays consumed even
 *     on failure: a flaky model must not burn unbounded retries within a
 *     window.
 */

import { existsSync } from 'node:fs';
import { mkdir, rename, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import {
	readKnowledge,
	resolveHiveKnowledgePath,
	resolveSwarmKnowledgePath,
} from '../hooks/knowledge-store.js';
import type {
	HiveKnowledgeEntry,
	SwarmKnowledgeEntry,
} from '../hooks/knowledge-types.js';
import {
	createSkillImproverLLMDelegate,
	type SkillImproverLLMDelegate,
} from '../hooks/skill-improver-llm-factory.js';
import { generateSkills, listSkills } from './skill-generator.js';
import {
	type QuotaWindow,
	releaseQuota,
	reserveQuota,
} from './skill-improver-quota.js';

export interface SkillImproverConfigInput {
	enabled: boolean;
	model: string | null;
	fallback_models: string[];
	max_calls_per_day: number;
	trigger: 'manual' | 'scheduled';
	targets: Array<'skills' | 'spec' | 'architect_prompt' | 'knowledge'>;
	write_mode: 'proposal' | 'draft_skills';
	require_user_approval: boolean;
	quota_window: QuotaWindow;
	allow_deterministic_fallback: boolean;
}

export type SkillImproverTarget =
	| 'skills'
	| 'spec'
	| 'architect_prompt'
	| 'knowledge';

export interface SkillImproveRequest {
	directory: string;
	config: SkillImproverConfigInput;
	targets?: SkillImproverTarget[];
	mode?: 'proposal' | 'draft_skills';
	maxCalls?: number;
	now?: Date;
	sessionId?: string;
	signal?: AbortSignal;
	/** Test-only seam: inject a delegate. When undefined, the service uses
	 *  createSkillImproverLLMDelegate(directory, sessionId) which returns
	 *  undefined unless swarmState.opencodeClient is wired. */
	delegate?: SkillImproverLLMDelegate;
}

export interface SkillImproveResult {
	ran: boolean;
	reason?: string;
	proposalPath?: string;
	source?: 'llm' | 'deterministic_fallback';
	quota: {
		date: string;
		calls_used: number;
		max_calls: number;
	};
	draftSkillsWritten?: Array<{
		slug: string;
		path: string;
		sourceKnowledgeIds: string[];
	}>;
	model?: string;
}

function timestampSlug(d: Date): string {
	return d.toISOString().replace(/[:.]/g, '-');
}

async function atomicWrite(p: string, content: string): Promise<void> {
	await mkdir(path.dirname(p), { recursive: true });
	const tmp = `${p}.tmp-${process.pid}-${Date.now()}`;
	await writeFile(tmp, content, 'utf-8');
	await rename(tmp, p);
}

interface InventorySnapshot {
	knowledge: { swarm: number; hive: number; archived: number };
	skills: { proposals: number; active: number };
	highConfidenceClusters: number;
	matureCandidates: SwarmKnowledgeEntry[];
}

async function gatherInventory(directory: string): Promise<InventorySnapshot> {
	const swarm = await readKnowledge<SwarmKnowledgeEntry>(
		resolveSwarmKnowledgePath(directory),
	);
	const hivePath = resolveHiveKnowledgePath();
	const hive = existsSync(hivePath)
		? await readKnowledge<HiveKnowledgeEntry>(hivePath)
		: [];
	const archived = [...swarm, ...hive].filter(
		(e) => e.status === 'archived',
	).length;
	const skills = await listSkills(directory);
	const matureCandidates = swarm
		.concat(hive as unknown as SwarmKnowledgeEntry[])
		.filter(
			(e) =>
				e.status !== 'archived' &&
				e.confidence >= 0.85 &&
				!e.generated_skill_slug &&
				(e.confirmed_by ?? []).length >= 2,
		);
	return {
		knowledge: { swarm: swarm.length, hive: hive.length, archived },
		skills: {
			proposals: skills.proposals.length,
			active: skills.active.length,
		},
		highConfidenceClusters: matureCandidates.length,
		matureCandidates,
	};
}

function buildSystemPrompt(
	targets: SkillImproverTarget[],
	cfg: SkillImproverConfigInput,
): string {
	return `You are skill_improver. Targets: ${targets.join(', ')}. Mode: ${cfg.write_mode}.

Output a single complete markdown proposal under 6000 chars. Sections required:
1. ## Inventory snapshot
2. ## Repeated ignored or violated directives (cite knowledge ids)
3. ## Concrete recommendations
4. ## Optional cluster suggestions for new draft skills (slug, title, source ids, target agents) — leave empty if none qualify
5. ## Risks and known limitations

Do NOT propose direct source-code edits. Do NOT call any tools. Return only the markdown body.`;
}

function buildUserPrompt(inv: InventorySnapshot): string {
	const matureRows = inv.matureCandidates
		.slice(0, 25)
		.map(
			(e) =>
				`- ${e.id} | conf=${e.confidence.toFixed(2)} | ${e.category} | "${e.lesson.slice(0, 140).replace(/\n/g, ' ')}"`,
		)
		.join('\n');
	return `INVENTORY
swarm_entries: ${inv.knowledge.swarm}
hive_entries: ${inv.knowledge.hive}
archived: ${inv.knowledge.archived}
draft_skills: ${inv.skills.proposals}
active_skills: ${inv.skills.active}
mature_uncompiled_clusters: ${inv.highConfidenceClusters}

TOP MATURE CANDIDATES (first 25):
${matureRows || '(none)'}
`;
}

function buildDeterministicProposal(args: {
	targets: SkillImproverTarget[];
	inventory: InventorySnapshot;
	model: string | null;
	now: Date;
}): string {
	const lines: string[] = [];
	lines.push('---');
	lines.push('source: deterministic_fallback');
	lines.push(`generated_at: ${args.now.toISOString()}`);
	lines.push(`targets: [${args.targets.join(', ')}]`);
	lines.push(`model: ${args.model ?? '(none — deterministic body)'}`);
	lines.push('---');
	lines.push('');
	lines.push('# Skill Improvement Proposal (deterministic fallback)');
	lines.push('');
	lines.push(
		'> No OpenCode LLM client was available when this proposal was generated. The body below is a deterministic inventory summary, not an LLM-derived analysis. To produce a real LLM proposal, run `skill_improve` from a session where the OpenCode runtime has wired `swarmState.opencodeClient`, or set `skill_improver.allow_deterministic_fallback: false` to force a hard failure instead of this fallback.',
	);
	lines.push('');
	lines.push('## Inventory snapshot');
	lines.push(
		`- Knowledge entries: swarm=${args.inventory.knowledge.swarm}, hive=${args.inventory.knowledge.hive}, archived=${args.inventory.knowledge.archived}`,
	);
	lines.push(
		`- Generated skills: proposals=${args.inventory.skills.proposals}, active=${args.inventory.skills.active}`,
	);
	lines.push(
		`- High-confidence un-skill'd clusters: ${args.inventory.highConfidenceClusters}`,
	);
	lines.push('');
	lines.push('## Recommendations');
	if (args.inventory.highConfidenceClusters > 0) {
		lines.push(
			`- Run \`skill_generate { mode: "draft" }\` to emit ${args.inventory.highConfidenceClusters} draft SKILL.md proposal(s).`,
		);
	}
	if (args.targets.includes('architect_prompt')) {
		lines.push(
			'- Manually review architect prompt against current high-priority directives.',
		);
	}
	if (args.targets.includes('spec')) {
		lines.push('- Audit `.swarm/spec.md` for drift.');
	}
	if (args.targets.includes('knowledge')) {
		lines.push(
			'- Archive low-confidence (< 0.3) entries with applied_explicit_count == 0 and shown_count > 5.',
		);
	}
	lines.push('');
	return lines.join('\n');
}

function buildLLMProposalFrame(args: {
	body: string;
	targets: SkillImproverTarget[];
	model: string | null;
	now: Date;
}): string {
	const lines: string[] = [];
	lines.push('---');
	lines.push('source: llm');
	lines.push(`generated_at: ${args.now.toISOString()}`);
	lines.push(`targets: [${args.targets.join(', ')}]`);
	if (args.model) lines.push(`model: ${args.model}`);
	lines.push('---');
	lines.push('');
	lines.push(args.body.trim());
	lines.push('');
	return lines.join('\n');
}

export async function runSkillImprover(
	req: SkillImproveRequest,
): Promise<SkillImproveResult> {
	const cfg = req.config;
	const now = req.now ?? new Date();
	const targets = (
		req.targets && req.targets.length > 0 ? req.targets : cfg.targets
	) as SkillImproverTarget[];
	const writeMode = req.mode ?? cfg.write_mode;
	const maxCalls = Math.max(
		1,
		Math.min(cfg.max_calls_per_day, req.maxCalls ?? 1),
	);
	const noQuota = {
		date: now.toISOString().slice(0, 10),
		calls_used: 0,
		max_calls: cfg.max_calls_per_day,
	};

	if (!cfg.enabled) {
		return {
			ran: false,
			reason: 'skill_improver.enabled is false',
			quota: noQuota,
		};
	}

	// Resolve the delegate BEFORE touching quota. Pre-flight refusal when
	// no delegate is available and fallback is disabled.
	const delegate =
		req.delegate ??
		createSkillImproverLLMDelegate(req.directory, req.sessionId);
	if (!delegate && !cfg.allow_deterministic_fallback) {
		return {
			ran: false,
			reason:
				'no_llm_client: skill_improver.allow_deterministic_fallback is false and no OpenCode client is wired. Run from a session where swarmState.opencodeClient is available, or enable allow_deterministic_fallback to use the offline path.',
			quota: noQuota,
		};
	}

	const reservation = await reserveQuota(req.directory, {
		nCalls: maxCalls,
		maxCalls: cfg.max_calls_per_day,
		window: cfg.quota_window,
		now,
	});
	if (!reservation.allowed) {
		return {
			ran: false,
			reason: reservation.reason ?? 'quota exhausted',
			quota: {
				date: reservation.state.date,
				calls_used: reservation.state.calls_used,
				max_calls: reservation.state.max_calls,
			},
		};
	}

	let inventory: InventorySnapshot;
	try {
		inventory = await gatherInventory(req.directory);
	} catch (err) {
		// Pre-network failure → release the reservation.
		await releaseQuota(req.directory, {
			nCalls: maxCalls,
			maxCalls: cfg.max_calls_per_day,
			window: cfg.quota_window,
			now,
		}).catch(() => {});
		return {
			ran: false,
			reason: `inventory_failed: ${err instanceof Error ? err.message : String(err)}`,
			quota: {
				date: reservation.state.date,
				calls_used: reservation.state.calls_used - maxCalls,
				max_calls: reservation.state.max_calls,
			},
		};
	}

	let body: string;
	let source: 'llm' | 'deterministic_fallback';
	if (delegate) {
		try {
			body = await delegate(
				buildSystemPrompt(targets, cfg),
				buildUserPrompt(inventory),
				req.signal,
			);
			if (!body || body.trim().length === 0) {
				throw new Error('empty LLM response');
			}
			source = 'llm';
		} catch (err) {
			// Network I/O began — slot stays consumed (anti-flake policy).
			return {
				ran: false,
				reason: `llm_call_failed: ${err instanceof Error ? err.message : String(err)}`,
				quota: {
					date: reservation.state.date,
					calls_used: reservation.state.calls_used,
					max_calls: reservation.state.max_calls,
				},
			};
		}
	} else {
		// allow_deterministic_fallback === true and no client wired.
		body = '';
		source = 'deterministic_fallback';
	}

	let draftSkillsWritten: SkillImproveResult['draftSkillsWritten'];
	if (writeMode === 'draft_skills' && inventory.matureCandidates.length > 0) {
		const gen = await generateSkills({
			directory: req.directory,
			mode: 'draft',
			minConfidence: 0.85,
			minConfirmations: 2,
		});
		draftSkillsWritten = gen.written.map((w) => ({
			slug: w.slug,
			path: w.path,
			sourceKnowledgeIds: w.sourceKnowledgeIds,
		}));
	}

	const proposalDir = path.join(
		req.directory,
		'.swarm',
		'skill-improver',
		'proposals',
	);
	const proposalFile = path.join(proposalDir, `${timestampSlug(now)}.md`);
	const finalBody =
		source === 'llm'
			? buildLLMProposalFrame({
					body,
					targets,
					model: cfg.model,
					now,
				})
			: buildDeterministicProposal({
					targets,
					inventory,
					model: cfg.model,
					now,
				});
	await atomicWrite(proposalFile, finalBody);

	return {
		ran: true,
		proposalPath: proposalFile,
		source,
		quota: {
			date: reservation.state.date,
			calls_used: reservation.state.calls_used,
			max_calls: reservation.state.max_calls,
		},
		draftSkillsWritten,
		model: cfg.model ?? undefined,
	};
}

export const _internals = {
	runSkillImprover,
	buildDeterministicProposal,
	buildLLMProposalFrame,
	buildSystemPrompt,
	buildUserPrompt,
	gatherInventory,
};
