/**
 * Skill-improver service — produces a proposal markdown reviewing accumulated
 * knowledge, generated skills, the spec, and the architect prompt. When an
 * LLM delegate is available the body is generated by the configured
 * skill_improver agent (issue #629). When no delegate is wired and the
 * `allow_deterministic_fallback` flag is true, a deterministic offline body
 * is written, clearly tagged.
 *
 * Quota policy:
 *   - Reservation happens BEFORE any network I/O.
 *   - If the delegate is undefined and fallback is disabled, no quota is
 *     reserved — we refuse early with `no_llm_client`.
 *   - If the delegate construction itself fails before any network call
 *     (extremely unlikely in practice), we release the quota.
 *   - Once `client.session.prompt` has begun, the slot stays consumed even
 *     on failure: a flaky model must not burn unbounded retries within a
 *     window.
 */

import { existsSync } from 'node:fs';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import type { EnrichmentQuotaOptions } from '../hooks/knowledge-curator.js';
import {
	readKnowledge,
	resolveHiveKnowledgePath,
	resolveSwarmKnowledgePath,
} from '../hooks/knowledge-store.js';
import type {
	HiveKnowledgeEntry,
	KnowledgeEntryBase,
	SwarmKnowledgeEntry,
} from '../hooks/knowledge-types.js';
import {
	createSkillImproverLLMDelegate,
	type SkillImproverLLMDelegate,
} from '../hooks/skill-improver-llm-factory.js';
import { hasActiveFullAuto } from '../state.js';
import {
	type AutoApplyResult,
	autoApplyProposals,
	DEFAULT_SKILL_MIN_CONFIDENCE,
	DEFAULT_SKILL_MIN_CONFIRMATIONS,
	generateSkills,
	listSkills,
	parseDraftFrontmatter,
	selectCandidateEntries,
} from './skill-generator.js';
import {
	type QuotaWindow,
	releaseQuota,
	reserveQuota,
} from './skill-improver-quota.js';
import {
	writeMotifProposals,
	writeSuccessMotifProposals,
} from './trajectory-cluster.js';
import { hardenUnactionableEntries } from './unactionable-hardening.js';

export interface SkillImproverConfigInput {
	enabled: boolean;
	model: string | null;
	fallback_models: string[];
	max_calls_per_day: number;
	trigger: 'manual' | 'scheduled';
	consolidation_interval_hours?: number;
	consolidation_max_calls_per_run?: number;
	targets: Array<'skills' | 'spec' | 'architect_prompt' | 'knowledge'>;
	write_mode: 'proposal' | 'draft_skills';
	require_user_approval: boolean;
	quota_window: QuotaWindow;
	allow_deterministic_fallback: boolean;
}

export type SkillImproverTarget =
	| 'skills'
	| 'spec'
	| 'architect_prompt'
	| 'knowledge';

export interface SkillImproveRequest {
	directory: string;
	config: SkillImproverConfigInput;
	targets?: SkillImproverTarget[];
	mode?: 'proposal' | 'draft_skills';
	maxCalls?: number;
	now?: Date;
	sessionId?: string;
	signal?: AbortSignal;
	/** Test-only seam: inject a delegate. When undefined, the service uses
	 *  createSkillImproverLLMDelegate(directory, sessionId) which returns
	 *  undefined unless swarmState.opencodeClient is wired. */
	delegate?: SkillImproverLLMDelegate;
	/** Dedicated quota for hardening quarantined knowledge entries. This is
	 *  separate from the skill_improver proposal quota above. */
	enrichmentQuota?: EnrichmentQuotaOptions;
	/** Validate generated draft skills when write_mode is draft_skills. */
	evaluateDrafts?: boolean;
	/** Consolidation callers stage proposals only and must never auto-apply. */
	allowAutoApply?: boolean;
}

export interface SkillImproveResult {
	ran: boolean;
	reason?: string;
	proposalPath?: string;
	source?: 'llm' | 'deterministic_fallback';
	quota: {
		date: string;
		calls_used: number;
		max_calls: number;
	};
	draftSkillsWritten?: Array<{
		slug: string;
		path: string;
		sourceKnowledgeIds: string[];
	}>;
	model?: string;
	/** Change 4 (Task 4.3): outcome of the unactionable-knowledge hardening pass. */
	unactionableHardening?: {
		hardened: number;
		retired: number;
		remaining: number;
	};
	/** Change 6 (Task 5.3): macro trajectory-motif proposals written this run. */
	macroMotifs?: {
		motifs: number;
		proposalsWritten: number;
	};
	/** #1234 Part 4: success workflow-motif proposals written this run. */
	successMotifs?: {
		motifs: number;
		proposalsWritten: number;
	};
	/** #1234 Part 3D: critic-gated auto-apply of proposals in full-auto mode. */
	autoApply?: AutoApplyResult;
}

function timestampSlug(d: Date): string {
	return d.toISOString().replace(/[:.]/g, '-');
}

async function atomicWrite(p: string, content: string): Promise<void> {
	await mkdir(path.dirname(p), { recursive: true });
	const tmp = `${p}.tmp-${process.pid}-${Date.now()}`;
	await writeFile(tmp, content, 'utf-8');
	await rename(tmp, p);
}

interface InventorySnapshot {
	knowledge: { swarm: number; hive: number; archived: number };
	skills: {
		proposals: number;
		active: number;
		stale: number;
		metadataReadable: number;
	};
	highConfidenceClusters: number;
	matureCandidates: KnowledgeEntryBase[];
	staleActiveSkills: Array<{ slug: string; reasons: string[] }>;
}

async function gatherInventory(directory: string): Promise<InventorySnapshot> {
	const swarm = await readKnowledge<SwarmKnowledgeEntry>(
		resolveSwarmKnowledgePath(directory),
	);
	const hivePath = resolveHiveKnowledgePath();
	const hive = existsSync(hivePath)
		? await readKnowledge<HiveKnowledgeEntry>(hivePath)
		: [];
	const archived = [...swarm, ...hive].filter(
		(e) => e.status === 'archived',
	).length;
	const skills = await listSkills(directory);
	const knowledgeById = new Map(
		[...swarm, ...hive].map((entry) => [entry.id, entry]),
	);
	const staleActiveSkills: Array<{ slug: string; reasons: string[] }> = [];
	let metadataReadable = 0;
	for (const skill of skills.active) {
		let content: string;
		try {
			content = await readFile(skill.path, 'utf-8');
		} catch {
			continue;
		}
		const fm = parseDraftFrontmatter(content);
		if (!fm) continue;
		metadataReadable += 1;
		const reasons: string[] = [];
		if (fm.sourceKnowledgeIds.length === 0) {
			reasons.push('missing_source_knowledge_ids');
		}
		if (!fm.generatedAt) {
			reasons.push('missing_generated_at');
		} else {
			const generatedAtMs = Date.parse(fm.generatedAt);
			if (!Number.isFinite(generatedAtMs)) {
				reasons.push('invalid_generated_at');
			} else {
				for (const id of fm.sourceKnowledgeIds) {
					const source = knowledgeById.get(id);
					if (!source) {
						reasons.push(`missing_source:${id}`);
						continue;
					}
					const updatedAtMs = Date.parse(source.updated_at);
					if (Number.isFinite(updatedAtMs) && updatedAtMs > generatedAtMs) {
						reasons.push(`updated_after_generation:${id}`);
					}
				}
			}
		}
		if (reasons.length > 0) {
			staleActiveSkills.push({
				slug: skill.slug,
				reasons: reasons.slice(0, 6),
			});
		}
	}
	const matureCandidates = await selectCandidateEntries(directory, {
		minConfidence: DEFAULT_SKILL_MIN_CONFIDENCE,
		minConfirmations: DEFAULT_SKILL_MIN_CONFIRMATIONS,
	});
	return {
		knowledge: { swarm: swarm.length, hive: hive.length, archived },
		skills: {
			proposals: skills.proposals.length,
			active: skills.active.length,
			stale: staleActiveSkills.length,
			metadataReadable,
		},
		highConfidenceClusters: matureCandidates.length,
		matureCandidates,
		staleActiveSkills,
	};
}

function buildSystemPrompt(
	targets: SkillImproverTarget[],
	cfg: SkillImproverConfigInput,
): string {
	return `You are skill_improver. Targets: ${targets.join(', ')}. Mode: ${cfg.write_mode}.

Output a single complete markdown proposal under 6000 chars. Sections required:
1. ## Inventory snapshot
2. ## Repeated ignored or violated directives (cite knowledge ids)
3. ## Concrete recommendations
4. ## Optional cluster suggestions for new draft skills (slug, title, source ids, target agents) — leave empty if none qualify
5. ## Risks and known limitations

Do NOT propose direct source-code edits. Do NOT call any tools. Return only the markdown body.`;
}

function buildUserPrompt(inv: InventorySnapshot): string {
	const matureRows = inv.matureCandidates
		.slice(0, 25)
		.map(
			(e) =>
				`- ${e.id} | conf=${e.confidence.toFixed(2)} | ${e.category} | "${e.lesson.slice(0, 140).replace(/\n/g, ' ')}"`,
		)
		.join('\n');
	return `INVENTORY
swarm_entries: ${inv.knowledge.swarm}
hive_entries: ${inv.knowledge.hive}
archived: ${inv.knowledge.archived}
draft_skills: ${inv.skills.proposals}
active_skills: ${inv.skills.active}
active_skills_with_readable_metadata: ${inv.skills.metadataReadable}
stale_active_skills: ${inv.skills.stale}
mature_uncompiled_clusters: ${inv.highConfidenceClusters}

TOP MATURE CANDIDATES (first 25):
${matureRows || '(none)'}

STALE ACTIVE SKILLS (first 10):
${
	inv.staleActiveSkills
		.slice(0, 10)
		.map((s) => `- ${s.slug} | ${s.reasons.join(', ')}`)
		.join('\n') || '(none)'
}
`;
}

function isAbortError(err: unknown): boolean {
	return (
		err instanceof Error &&
		(err.name === 'AbortError' || err.message === 'skill_improver_aborted')
	);
}

function throwIfAborted(signal: AbortSignal | undefined): void {
	if (!signal?.aborted) return;
	const err = new Error('skill_improver_aborted');
	err.name = 'AbortError';
	throw err;
}

function buildDeterministicProposal(args: {
	targets: SkillImproverTarget[];
	inventory: InventorySnapshot;
	model: string | null;
	now: Date;
}): string {
	const lines: string[] = [];
	lines.push('---');
	lines.push('source: deterministic_fallback');
	lines.push(`generated_at: ${args.now.toISOString()}`);
	lines.push(`targets: [${args.targets.join(', ')}]`);
	lines.push(`model: ${args.model ?? '(none — deterministic body)'}`);
	lines.push('---');
	lines.push('');
	lines.push('# Skill Improvement Proposal (deterministic fallback)');
	lines.push('');
	lines.push(
		'> No OpenCode LLM client was available when this proposal was generated. The body below is a deterministic inventory summary, not an LLM-derived analysis. To produce a real LLM proposal, run `skill_improve` from a session where the OpenCode runtime has wired `swarmState.opencodeClient`, or set `skill_improver.allow_deterministic_fallback: false` to force a hard failure instead of this fallback.',
	);
	lines.push('');
	lines.push('## Inventory snapshot');
	lines.push(
		`- Knowledge entries: swarm=${args.inventory.knowledge.swarm}, hive=${args.inventory.knowledge.hive}, archived=${args.inventory.knowledge.archived}`,
	);
	lines.push(
		`- Generated skills: proposals=${args.inventory.skills.proposals}, active=${args.inventory.skills.active}`,
	);
	lines.push(
		`- Active skills with readable metadata: ${args.inventory.skills.metadataReadable} (stale=${args.inventory.skills.stale})`,
	);
	lines.push(
		`- High-confidence un-skill'd clusters: ${args.inventory.highConfidenceClusters}`,
	);
	if (args.inventory.staleActiveSkills.length > 0) {
		lines.push(
			`- Stale active skills: ${args.inventory.staleActiveSkills.map((s) => s.slug).join(', ')}`,
		);
	}
	lines.push('');
	lines.push('## Recommendations');
	if (args.inventory.highConfidenceClusters > 0) {
		lines.push(
			`- Run \`skill_generate { mode: "draft" }\` to emit ${args.inventory.highConfidenceClusters} draft SKILL.md proposal(s).`,
		);
	}
	if (args.targets.includes('architect_prompt')) {
		lines.push(
			'- Manually review architect prompt against current high-priority directives.',
		);
	}
	if (args.targets.includes('spec')) {
		lines.push('- Audit `.swarm/spec.md` for drift.');
	}
	if (args.targets.includes('knowledge')) {
		lines.push(
			'- Archive low-confidence (< 0.3) entries with applied_explicit_count == 0 and shown_count > 5.',
		);
	}
	lines.push('');
	return lines.join('\n');
}

function buildLLMProposalFrame(args: {
	body: string;
	targets: SkillImproverTarget[];
	model: string | null;
	now: Date;
}): string {
	const lines: string[] = [];
	lines.push('---');
	lines.push('source: llm');
	lines.push(`generated_at: ${args.now.toISOString()}`);
	lines.push(`targets: [${args.targets.join(', ')}]`);
	if (args.model) lines.push(`model: ${args.model}`);
	lines.push('---');
	lines.push('');
	lines.push(args.body.trim());
	lines.push('');
	return lines.join('\n');
}

export async function runSkillImprover(
	req: SkillImproveRequest,
): Promise<SkillImproveResult> {
	const cfg = req.config;
	const now = req.now ?? new Date();
	const targets = (
		req.targets && req.targets.length > 0 ? req.targets : cfg.targets
	) as SkillImproverTarget[];
	const writeMode = req.mode ?? cfg.write_mode;
	const maxCalls = Math.max(
		1,
		Math.min(cfg.max_calls_per_day, req.maxCalls ?? 1),
	);
	const noQuota = {
		date: now.toISOString().slice(0, 10),
		calls_used: 0,
		max_calls: cfg.max_calls_per_day,
	};

	if (!cfg.enabled) {
		return {
			ran: false,
			reason: 'skill_improver.enabled is false',
			quota: noQuota,
		};
	}
	if (req.signal?.aborted) {
		return {
			ran: false,
			reason: 'skill_improver aborted',
			quota: noQuota,
		};
	}

	// Resolve the delegate BEFORE touching quota. Pre-flight refusal when
	// no delegate is available and fallback is disabled.
	const delegate =
		req.delegate ??
		createSkillImproverLLMDelegate(req.directory, req.sessionId);
	if (!delegate && !cfg.allow_deterministic_fallback) {
		return {
			ran: false,
			reason:
				'no_llm_client: skill_improver.allow_deterministic_fallback is false and no OpenCode client is wired. Run from a session where swarmState.opencodeClient is available, or enable allow_deterministic_fallback to use the offline path.',
			quota: noQuota,
		};
	}

	const reservation = await reserveQuota(req.directory, {
		nCalls: maxCalls,
		maxCalls: cfg.max_calls_per_day,
		window: cfg.quota_window,
		now,
	});
	if (!reservation.allowed) {
		return {
			ran: false,
			reason: reservation.reason ?? 'quota exhausted',
			quota: {
				date: reservation.state.date,
				calls_used: reservation.state.calls_used,
				max_calls: reservation.state.max_calls,
			},
		};
	}

	let networkStarted = false;
	let sideEffectsStarted = false;
	const reservationQuota = {
		date: reservation.state.date,
		calls_used: reservation.state.calls_used,
		max_calls: reservation.state.max_calls,
	};
	const releaseReservedQuota = async () => {
		const released = await releaseQuota(req.directory, {
			nCalls: maxCalls,
			maxCalls: cfg.max_calls_per_day,
			window: cfg.quota_window,
			now,
		}).catch(() => ({
			...reservation.state,
			calls_used: Math.max(0, reservation.state.calls_used - maxCalls),
		}));
		return {
			date: released.date,
			calls_used: released.calls_used,
			max_calls: released.max_calls,
		};
	};
	const abortResult = async (): Promise<SkillImproveResult> => ({
		ran: false,
		reason: 'skill_improver aborted',
		quota:
			networkStarted || sideEffectsStarted
				? reservationQuota
				: await releaseReservedQuota(),
	});

	let inventory: InventorySnapshot;
	try {
		throwIfAborted(req.signal);
		inventory = await gatherInventory(req.directory);
		throwIfAborted(req.signal);
	} catch (err) {
		if (isAbortError(err)) {
			return await abortResult();
		}
		// Pre-network failure → release the reservation.
		await releaseQuota(req.directory, {
			nCalls: maxCalls,
			maxCalls: cfg.max_calls_per_day,
			window: cfg.quota_window,
			now,
		}).catch(() => {});
		return {
			ran: false,
			reason: `inventory_failed: ${err instanceof Error ? err.message : String(err)}`,
			quota: {
				date: reservation.state.date,
				calls_used: reservation.state.calls_used - maxCalls,
				max_calls: reservation.state.max_calls,
			},
		};
	}

	let body: string;
	let source: 'llm' | 'deterministic_fallback';
	if (delegate) {
		try {
			throwIfAborted(req.signal);
			networkStarted = true;
			body = await delegate(
				buildSystemPrompt(targets, { ...cfg, write_mode: writeMode }),
				buildUserPrompt(inventory),
				req.signal,
			);
			throwIfAborted(req.signal);
			if (!body || body.trim().length === 0) {
				throw new Error('empty LLM response');
			}
			source = 'llm';
		} catch (err) {
			if (isAbortError(err)) {
				return await abortResult();
			}
			// Network I/O began — slot stays consumed (anti-flake policy).
			return {
				ran: false,
				reason: `llm_call_failed: ${err instanceof Error ? err.message : String(err)}`,
				quota: {
					date: reservation.state.date,
					calls_used: reservation.state.calls_used,
					max_calls: reservation.state.max_calls,
				},
			};
		}
	} else {
		// allow_deterministic_fallback === true and no client wired.
		try {
			throwIfAborted(req.signal);
		} catch (err) {
			if (isAbortError(err)) {
				return await abortResult();
			}
			throw err;
		}
		body = '';
		source = 'deterministic_fallback';
	}

	let draftSkillsWritten: SkillImproveResult['draftSkillsWritten'];
	if (writeMode === 'draft_skills' && inventory.matureCandidates.length > 0) {
		try {
			throwIfAborted(req.signal);
		} catch (err) {
			if (isAbortError(err)) {
				return await abortResult();
			}
			throw err;
		}
		sideEffectsStarted = true;
		const gen = await generateSkills({
			directory: req.directory,
			mode: 'draft',
			minConfidence: DEFAULT_SKILL_MIN_CONFIDENCE,
			minConfirmations: DEFAULT_SKILL_MIN_CONFIRMATIONS,
			evaluate: req.evaluateDrafts ?? false,
		});
		draftSkillsWritten = gen.written.map((w) => ({
			slug: w.slug,
			path: w.path,
			sourceKnowledgeIds: w.sourceKnowledgeIds,
		}));
	}
	try {
		throwIfAborted(req.signal);
	} catch (err) {
		if (isAbortError(err)) {
			return await abortResult();
		}
		throw err;
	}

	const proposalDir = path.join(
		req.directory,
		'.swarm',
		'skill-improver',
		'proposals',
	);
	const proposalFile = path.join(proposalDir, `${timestampSlug(now)}.md`);
	const finalBody =
		source === 'llm'
			? buildLLMProposalFrame({
					body,
					targets,
					model: cfg.model,
					now,
				})
			: buildDeterministicProposal({
					targets,
					inventory,
					model: cfg.model,
					now,
				});
	sideEffectsStarted = true;
	await atomicWrite(proposalFile, finalBody);

	// Change 4 (Task 4.3): hardening pass over the unactionable queue. Each LLM
	// attempt is individually quota-gated inside enrichLessonToV3 using the
	// dedicated knowledge-enrichment budget, while this service's own proposal
	// call remains governed by skill_improver.max_calls_per_day. Skipped without
	// a delegate — auto-retiring entries without an attempt would be wrong.
	// Fail-open: a hardening failure never fails the improver run.
	let unactionableHardening: SkillImproveResult['unactionableHardening'];
	if (delegate) {
		unactionableHardening = await hardenUnactionableEntries({
			directory: req.directory,
			llmDelegate: delegate,
			quota: req.enrichmentQuota,
		});
	}

	// Macro reflector (Change 6, Task 5.3): cluster recurring failure motifs from
	// the recent trajectory window and emit skill PROPOSALS (never active skills).
	// Deterministic + read-only over the store; no LLM call, no quota draw.
	const motifResult = await writeMotifProposals(req.directory);
	const macroMotifs = {
		motifs: motifResult.motifs,
		proposalsWritten: motifResult.proposalsWritten.length,
	};

	// #1234 Part 4: mine recurring successful tool-sequences and emit
	// workflow-type skill proposals. Same cadence, same proposals dir, no LLM.
	const successMotifResult = await writeSuccessMotifProposals(req.directory);
	const successMotifs = {
		motifs: successMotifResult.motifs,
		proposalsWritten: successMotifResult.proposalsWritten.length,
	};

	// #1234 Part 3D: critic-gated auto-apply of proposals in full-auto mode.
	// Only runs when THIS session is in full-auto AND an LLM delegate is available
	// (the delegate acts as the critic gate). The explicit `req.sessionId` check
	// is load-bearing: hasActiveFullAuto(undefined) scans ALL sessions, so without
	// it a request lacking a sessionId would auto-apply whenever any other session
	// happened to be in full-auto (cross-session leak). Fail-open: never blocks.
	let autoApply: AutoApplyResult | undefined;
	if (
		req.allowAutoApply !== false &&
		delegate &&
		req.sessionId &&
		hasActiveFullAuto(req.sessionId)
	) {
		try {
			autoApply = await autoApplyProposals(req.directory, delegate);
		} catch {
			// fail-open
		}
	}

	return {
		ran: true,
		proposalPath: proposalFile,
		source,
		quota: {
			date: reservation.state.date,
			calls_used: reservation.state.calls_used,
			max_calls: reservation.state.max_calls,
		},
		draftSkillsWritten,
		model: cfg.model ?? undefined,
		unactionableHardening,
		macroMotifs,
		successMotifs,
		autoApply,
	};
}

export const _internals = {
	runSkillImprover,
	buildDeterministicProposal,
	buildLLMProposalFrame,
	buildSystemPrompt,
	buildUserPrompt,
	gatherInventory,
};
