/**
 * Tests for skill_regenerate tool and regenerateSkill service.
 *
 * Covers:
 * - regenerateSkill: happy path re-clustering, skill-not-found, invalid slug,
 *   no source IDs in frontmatter fallback, no matching entries, re-stamping,
 *   entry count reporting
 * - skill_regenerate tool: delegation happy path, missing slug error
 */

import { afterEach, beforeEach, describe, expect, it, mock } from 'bun:test';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import * as fs from 'node:fs/promises';
import { mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { resolveSwarmKnowledgePath } from '../../../src/hooks/knowledge-store';
import type { SwarmKnowledgeEntry } from '../../../src/hooks/knowledge-types';
import {
	regenerateSkill,
	_internals as serviceInternals,
} from '../../../src/services/skill-generator';
import {
	skill_regenerate,
	_internals as toolInternals,
} from '../../../src/tools/skill-regenerate';

let tmp: string;
let originalCwd: string;

beforeEach(async () => {
	mock.restore();
	tmp = await fs.realpath(
		await fs.mkdtemp(path.join(tmpdir(), 'swarm-skill-regen-')),
	);
	originalCwd = process.cwd();
	process.chdir(tmp);
});

afterEach(async () => {
	process.chdir(originalCwd);
	rmSync(tmp, { recursive: true, force: true });
	mock.restore();
});

// ---------------------------------------------------------------------------
// Helper: create a valid active skill directory with SKILL.md
// ---------------------------------------------------------------------------
async function createActiveSkill(
	slug: string,
	frontmatterContent: string,
): Promise<string> {
	const skillDir = path.join(tmp, '.opencode', 'skills', 'generated', slug);
	await mkdir(skillDir, { recursive: true });
	await writeFile(path.join(skillDir, 'SKILL.md'), frontmatterContent, 'utf-8');
	return skillDir;
}

// ---------------------------------------------------------------------------
// Helper: make a swarm knowledge entry
// ---------------------------------------------------------------------------
function makeEntry(
	id: string,
	overrides: Partial<SwarmKnowledgeEntry> = {},
): SwarmKnowledgeEntry {
	return {
		id,
		tier: 'swarm',
		lesson: 'always declare scope before coder delegation',
		category: 'process',
		tags: ['scope', 'delegation'],
		scope: 'global',
		confidence: 0.9,
		status: 'established',
		confirmed_by: [
			{
				phase_number: 1,
				confirmed_at: new Date().toISOString(),
				project_name: 'test',
			},
			{
				phase_number: 2,
				confirmed_at: new Date().toISOString(),
				project_name: 'test',
			},
		],
		retrieval_outcomes: {
			applied_count: 0,
			succeeded_after_count: 0,
			failed_after_count: 0,
		},
		schema_version: 2,
		created_at: new Date().toISOString(),
		updated_at: new Date().toISOString(),
		project_name: 'test',
		triggers: ['coder delegation'],
		required_actions: ['call declare_scope'],
		forbidden_actions: ['heredoc bash writes'],
		applies_to_agents: ['coder'],
		directive_priority: 'critical',
		...overrides,
	};
}

// ---------------------------------------------------------------------------
// Helper: seed swarm knowledge.jsonl
// ---------------------------------------------------------------------------
async function seed(entries: SwarmKnowledgeEntry[]): Promise<void> {
	const dir = path.join(tmp, '.swarm');
	await mkdir(dir, { recursive: true });
	const lines = entries.map((e) => JSON.stringify(e)).join('\n') + '\n';
	await writeFile(resolveSwarmKnowledgePath(tmp), lines, 'utf-8');
}

// ---------------------------------------------------------------------------
// Helper: build a valid frontmatter string with source IDs
// ---------------------------------------------------------------------------
function buildFrontmatter(slug: string, ids: string[]): string {
	const idsYaml = ids.map((id) => `  - ${id}`).join('\n');
	return `---
name: ${slug}
description: "Test skill"
generated_from_knowledge:
${idsYaml}
source_knowledge_ids:
${idsYaml}
generated_at: 2000-01-01T00:00:00.000Z
confidence: 0.90
status: active
---

<!-- generated by opencode-swarm skill-generator. Do not edit by hand; edits will be preserved on regeneration only with controlled update mode. -->

# Test Skill

## Trigger
- coder delegation

## Required Procedure
- call declare_scope

## Forbidden Shortcuts
- (none recorded)

## Delegation Template

When delegating a task affected by this skill, include:

\`\`\`
SKILLS: file:.opencode/skills/generated/${slug}/SKILL.md
\`\`\`

## Reviewer Checks
- Verify each required action above appears in the diff.

## Source Knowledge IDs
${ids.map((id) => `- ${id} — lesson text`).join('\n')}
`;
}

// ============================================================================
// regenerateSkill tests
// ============================================================================

describe('regenerateSkill', () => {
	// ------------------------------------------------------------------
	// Test 1: Happy path — re-clusters knowledge and rewrites SKILL.md
	// ------------------------------------------------------------------
	it('happy path: re-clusters source entries and rewrites SKILL.md', async () => {
		const entry1 = makeEntry('entry-regen-1', {
			tags: ['testing', 'scope'],
			lesson: 'always write tests for scope guard',
			triggers: ['scope guard'],
			required_actions: ['add tests for scope guard'],
			forbidden_actions: [],
		});
		const entry2 = makeEntry('entry-regen-2', {
			tags: ['testing', 'delegation'],
			lesson: 'always write tests for delegation pattern',
			triggers: ['delegation'],
			required_actions: ['add tests for delegation'],
			forbidden_actions: [],
		});
		await seed([entry1, entry2]);

		const skillContent = buildFrontmatter('testing-skill', [
			'entry-regen-1',
			'entry-regen-2',
		]);
		const skillDir = await createActiveSkill('testing-skill', skillContent);
		const skillPath = path.join(skillDir, 'SKILL.md');

		const result = await regenerateSkill(tmp, 'testing-skill');

		expect(result.regenerated).toBe(true);
		expect(result.entryCount).toBe(2);
		expect(result.path).toBe(skillPath);

		// Verify SKILL.md was rewritten with new content
		const newContent = readFileSync(skillPath, 'utf-8');
		expect(newContent).toContain('generated by opencode-swarm skill-generator');
		expect(newContent).toContain('## Trigger');
		expect(newContent).toContain('## Required Procedure');
		expect(newContent).toContain('source_knowledge_ids:');
		expect(newContent).toMatch(/^generated_at:\s+\S+/m);
		expect(newContent).not.toContain('generated_at: 2000-01-01T00:00:00.000Z');
	});

	// ------------------------------------------------------------------
	// Test 2: Skill not found — returns { regenerated: false }
	// ------------------------------------------------------------------
	it('skill not found: returns regenerated false with reason', async () => {
		const result = await regenerateSkill(tmp, 'nonexistent-skill');

		expect(result.regenerated).toBe(false);
		expect(result.entryCount).toBe(0);
		expect(result.reason).toBe('active skill not found');
	});

	// ------------------------------------------------------------------
	// Test 3: Invalid slug — returns { regenerated: false }
	// ------------------------------------------------------------------
	it('invalid slug: returns regenerated false with reason "invalid slug"', async () => {
		const result = await regenerateSkill(tmp, '');

		expect(result.regenerated).toBe(false);
		expect(result.entryCount).toBe(0);
		expect(result.reason).toBe('invalid slug');
	});

	it('slug with path traversal chars: sanitized to safe form, then rejected as invalid', async () => {
		// sanitizeSlug('..') → '' (empty after trimming), isValidSlug('') → false
		const result = await regenerateSkill(tmp, '..');
		expect(result.regenerated).toBe(false);
		expect(result.reason).toBe('invalid slug');
	});

	// ------------------------------------------------------------------
	// Test 4: SKILL.md with no source IDs in frontmatter — falls back to slug-token matching
	// ------------------------------------------------------------------
	it('no source IDs in frontmatter: falls back to slug-token matching', async () => {
		// Entry whose tags/lesson contain "testing" token matching slug "testing-skill"
		const entry1 = makeEntry('fallback-entry-1', {
			tags: ['testing', 'scope'],
			lesson: 'always write tests for scope guard',
			triggers: ['scope guard'],
			required_actions: ['add tests for scope guard'],
		});
		const entry2 = makeEntry('fallback-entry-2', {
			tags: ['testing', 'delegation'],
			lesson: 'always write tests for delegation pattern',
			triggers: ['delegation'],
			required_actions: ['add tests for delegation'],
		});
		await seed([entry1, entry2]);

		// Frontmatter with no generated_from_knowledge IDs
		const noIdsContent = `---
name: testing-skill
description: "Test skill"
confidence: 0.90
status: active
---

<!-- generated by opencode-swarm skill-generator. Do not edit by hand -->

# Test Skill

## Trigger
- coder delegation
`;
		const skillDir = await createActiveSkill('testing-skill', noIdsContent);
		const skillPath = path.join(skillDir, 'SKILL.md');

		const result = await regenerateSkill(tmp, 'testing-skill');

		expect(result.regenerated).toBe(true);
		expect(result.entryCount).toBe(2);
		expect(result.path).toBe(skillPath);

		// Verify the file was rewritten
		const newContent = readFileSync(skillPath, 'utf-8');
		expect(newContent).toContain('generated by opencode-swarm skill-generator');
	});

	// ------------------------------------------------------------------
	// Test 5: No matching knowledge entries — returns { regenerated: false, reason }
	// ------------------------------------------------------------------
	it('no matching entries: returns regenerated false with reason', async () => {
		// No entries seeded at all
		const noIdsContent = `---
name: empty-skill
description: "Empty skill"
confidence: 0.90
status: active
---

<!-- generated by opencode-swarm skill-generator. Do not edit by hand -->

# Empty Skill
`;
		await createActiveSkill('empty-skill', noIdsContent);

		const result = await regenerateSkill(tmp, 'empty-skill');

		expect(result.regenerated).toBe(false);
		expect(result.entryCount).toBe(0);
		expect(result.reason).toBe(
			'no matching knowledge entries found for re-clustering',
		);
	});

	// ------------------------------------------------------------------
	// Test 6: Source entries re-stamped after regeneration
	// ------------------------------------------------------------------
	it('source entries are re-stamped with generated_skill_slug and generated_skill_path after regeneration', async () => {
		const entry1 = makeEntry('stamp-entry-1', {
			tags: ['scope'],
			lesson: 'scope declaration lesson',
			required_actions: ['declare scope'],
		});
		const entry2 = makeEntry('stamp-entry-2', {
			tags: ['scope'],
			lesson: 'scope verification lesson',
			required_actions: ['verify scope'],
		});
		await seed([entry1, entry2]);

		const skillContent = buildFrontmatter('stamp-skill', [
			'stamp-entry-1',
			'stamp-entry-2',
		]);
		await createActiveSkill('stamp-skill', skillContent);

		await regenerateSkill(tmp, 'stamp-skill');

		// Read the knowledge.jsonl and verify entries are stamped
		const knowledgeContent = readFileSync(
			resolveSwarmKnowledgePath(tmp),
			'utf-8',
		)
			.trim()
			.split('\n')
			.map((l) => JSON.parse(l));

		const stamped1 = knowledgeContent.find(
			(e: any) => e.id === 'stamp-entry-1',
		);
		const stamped2 = knowledgeContent.find(
			(e: any) => e.id === 'stamp-entry-2',
		);

		expect(stamped1?.generated_skill_slug).toBe('stamp-skill');
		expect(stamped1?.generated_skill_path).toContain(
			'.opencode/skills/generated/stamp-skill/SKILL.md',
		);
		expect(stamped2?.generated_skill_slug).toBe('stamp-skill');
		expect(stamped2?.generated_skill_path).toContain(
			'.opencode/skills/generated/stamp-skill/SKILL.md',
		);
	});

	// ------------------------------------------------------------------
	// Test 7: Entry count reported correctly
	// ------------------------------------------------------------------
	it('entry count matches the number of matched/re-clustered entries', async () => {
		const entry1 = makeEntry('count-entry-1', {
			tags: ['process'],
			lesson: 'process lesson one',
		});
		const entry2 = makeEntry('count-entry-2', {
			tags: ['process'],
			lesson: 'process lesson two',
		});
		const entry3 = makeEntry('count-entry-3', {
			tags: ['process'],
			lesson: 'process lesson three',
		});
		await seed([entry1, entry2, entry3]);

		const skillContent = buildFrontmatter('count-skill', [
			'count-entry-1',
			'count-entry-2',
			'count-entry-3',
		]);
		await createActiveSkill('count-skill', skillContent);

		const result = await regenerateSkill(tmp, 'count-skill');

		expect(result.regenerated).toBe(true);
		expect(result.entryCount).toBe(3);
	});

	it('entry count is 1 when only one of multiple frontmatter IDs is found in knowledge store', async () => {
		const entry1 = makeEntry('partial-entry-1', {
			tags: ['process'],
			lesson: 'process lesson one',
		});
		// entry2 does NOT exist in the knowledge store
		await seed([entry1]);

		const skillContent = buildFrontmatter('partial-skill', [
			'partial-entry-1',
			'nonexistent-entry-2',
		]);
		await createActiveSkill('partial-skill', skillContent);

		const result = await regenerateSkill(tmp, 'partial-skill');

		expect(result.regenerated).toBe(true);
		expect(result.entryCount).toBe(1);
	});

	// ------------------------------------------------------------------
	// Test: Mixed active/archived entries — archived excluded from regeneration
	// ------------------------------------------------------------------
	it('excludes archived entries from regenerated SKILL.md content', async () => {
		const activeEntry = makeEntry('mixed-active-1', {
			lesson: 'always verify scope before delegation',
			tags: ['scope', 'delegation'],
			triggers: ['scope guard'],
			required_actions: ['verify scope before delegating'],
			status: 'established',
		});
		const archivedEntry = makeEntry('mixed-archived-2', {
			lesson: 'deprecated: always use shell for file ops',
			tags: ['shell', 'deprecated'],
			triggers: ['shell commands'],
			required_actions: ['use shell for file operations'],
			status: 'archived',
		});
		await seed([activeEntry, archivedEntry]);

		const skillContent = buildFrontmatter('mixed-status-skill', [
			'mixed-active-1',
			'mixed-archived-2',
		]);
		const skillDir = await createActiveSkill(
			'mixed-status-skill',
			skillContent,
		);
		const skillPath = path.join(skillDir, 'SKILL.md');

		const result = await regenerateSkill(tmp, 'mixed-status-skill');

		expect(result.regenerated).toBe(true);
		expect(result.entryCount).toBe(1);

		const newContent = readFileSync(skillPath, 'utf-8');
		// Active entry lesson must appear in regenerated content
		expect(newContent).toContain('always verify scope before delegation');
		// Archived entry lesson must NOT appear
		expect(newContent).not.toContain(
			'deprecated: always use shell for file ops',
		);
	});

	// ------------------------------------------------------------------
	// Test: All archived but partial match — retires after filtering
	// ------------------------------------------------------------------
	it('retires skill when all matched entries are archived but not all source IDs matched', async () => {
		const archivedEntry = makeEntry('partial-archived-1', {
			lesson: 'obsolete rule about caching',
			tags: ['caching', 'obsolete'],
			status: 'archived',
		});
		// Only 1 of 2 frontmatter IDs exists, and it's archived.
		await seed([archivedEntry]);

		const skillContent = buildFrontmatter('partial-archived-skill', [
			'partial-archived-1',
			'nonexistent-archived-2',
		]);
		await createActiveSkill('partial-archived-skill', skillContent);

		const result = await regenerateSkill(tmp, 'partial-archived-skill');

		expect(result.regenerated).toBe(false);
		expect(result.retired).toBe(true);
		expect(result.entryCount).toBe(0);
		expect(result.reason).toContain('archived');
	});

	// ------------------------------------------------------------------
	// Test: All entries archived, all source IDs matched — early-retirement path
	// ------------------------------------------------------------------
	it('retires skill when all source entries are archived and all IDs matched (early-retirement)', async () => {
		const archivedEntry1 = makeEntry('all-archived-swarm-1', {
			lesson: 'stale lesson about pre-commit hooks',
			tags: ['hooks', 'stale'],
			status: 'archived',
		});
		const archivedEntry2 = makeEntry('all-archived-swarm-2', {
			lesson: 'stale lesson about branch naming',
			tags: ['branching', 'stale'],
			status: 'archived',
		});
		await seed([archivedEntry1, archivedEntry2]);

		const skillContent = buildFrontmatter('all-archived-skill', [
			'all-archived-swarm-1',
			'all-archived-swarm-2',
		]);
		await createActiveSkill('all-archived-skill', skillContent);

		const result = await regenerateSkill(tmp, 'all-archived-skill');

		expect(result.regenerated).toBe(false);
		expect(result.retired).toBe(true);
		expect(result.entryCount).toBe(0);
		expect(result.reason).toContain('archived');
	});
});

// ============================================================================
// skill_regenerate tool tests
// ============================================================================

describe('skill_regenerate tool', () => {
	// ------------------------------------------------------------------
	// Test 1: Happy path delegation
	// ------------------------------------------------------------------
	it('happy path: delegates to regenerateSkill and returns JSON result', async () => {
		const entry1 = makeEntry('tool-entry-1', {
			tags: ['scope'],
			lesson: 'tool delegation test lesson',
		});
		const entry2 = makeEntry('tool-entry-2', {
			tags: ['scope'],
			lesson: 'tool delegation test second lesson',
		});
		await seed([entry1, entry2]);

		const skillContent = buildFrontmatter('tool-test-skill', [
			'tool-entry-1',
			'tool-entry-2',
		]);
		await createActiveSkill('tool-test-skill', skillContent);

		// process.chdir(tmp) in beforeEach ensures process.cwd() returns tmp
		const result = await skill_regenerate.execute({ slug: 'tool-test-skill' });
		const parsed = JSON.parse(result);

		expect(parsed.regenerated).toBe(true);
		expect(parsed.entryCount).toBe(2);
	});

	// ------------------------------------------------------------------
	// Test 2: Missing slug returns error
	// ------------------------------------------------------------------
	it('missing slug returns error JSON with reason "slug required"', async () => {
		const result = await skill_regenerate.execute({});
		const parsed = JSON.parse(result);

		expect(parsed.regenerated).toBe(false);
		expect(parsed.reason).toBe('slug required');
	});

	it('null slug returns error JSON with reason "slug required"', async () => {
		const result = await skill_regenerate.execute({ slug: null });
		const parsed = JSON.parse(result);

		expect(parsed.regenerated).toBe(false);
		expect(parsed.reason).toBe('slug required');
	});

	it('undefined slug returns error JSON with reason "slug required"', async () => {
		const result = await skill_regenerate.execute({ slug: undefined });
		const parsed = JSON.parse(result);

		expect(parsed.regenerated).toBe(false);
		expect(parsed.reason).toBe('slug required');
	});

	it('empty string slug returns error JSON with reason "slug required"', async () => {
		const result = await skill_regenerate.execute({ slug: '' });
		const parsed = JSON.parse(result);

		expect(parsed.regenerated).toBe(false);
		expect(parsed.reason).toBe('slug required');
	});
});

// ============================================================================
// _internals DI seam verification
// ============================================================================

describe('_internals seam for skill_regenerate', () => {
	it('exposes skill_regenerate via _internals', () => {
		expect(toolInternals.skill_regenerate).toBeDefined();
		expect(typeof toolInternals.skill_regenerate.execute).toBe('function');
	});
});
