/**
 * Tests for autoApplyProposals (#1234 Part 3D).
 */

import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { autoApplyProposals } from '../../../src/services/skill-generator.js';

function writeProposal(dir: string, slug: string, content: string): void {
	const proposalsDir = path.join(dir, '.swarm', 'skills', 'proposals');
	fs.mkdirSync(proposalsDir, { recursive: true });
	fs.writeFileSync(path.join(proposalsDir, `${slug}.md`), content, 'utf-8');
}

function writeActiveSkill(dir: string, slug: string): void {
	const activeDir = path.join(dir, '.opencode', 'skills', 'generated', slug);
	fs.mkdirSync(activeDir, { recursive: true });
	fs.writeFileSync(
		path.join(activeDir, 'SKILL.md'),
		'<!-- generated by opencode-swarm skill-generator -->\n# Active Skill\n',
		'utf-8',
	);
}

const PROPOSAL_CONTENT = [
	'---',
	'name: test-skill',
	'description: A test skill',
	'status: draft',
	'version: 1',
	'skill_origin: knowledge',
	'source_knowledge_ids:',
	'  - KN-001',
	'---',
	'<!-- generated by opencode-swarm skill-generator -->',
	'# Test Skill',
	'Always run tests before committing.',
].join('\n');

describe('autoApplyProposals', () => {
	let dir: string;

	beforeEach(() => {
		dir = fs.mkdtempSync(path.join(os.tmpdir(), 'auto-apply-'));
		fs.mkdirSync(path.join(dir, '.swarm'), { recursive: true });
	});

	afterEach(() => {
		fs.rmSync(dir, { recursive: true, force: true });
	});

	it('returns empty when no proposals exist', async () => {
		const delegate = async () => 'APPROVE';
		const result = await autoApplyProposals(dir, delegate);
		expect(result.approved).toHaveLength(0);
		expect(result.rejected).toHaveLength(0);
		expect(result.skipped).toHaveLength(0);
	});

	it('activates approved proposals', async () => {
		writeProposal(dir, 'test-approved', PROPOSAL_CONTENT);
		const delegate = async () => 'APPROVE';
		const result = await autoApplyProposals(dir, delegate);
		expect(result.approved).toContain('test-approved');

		const activePath = path.join(
			dir,
			'.opencode',
			'skills',
			'generated',
			'test-approved',
			'SKILL.md',
		);
		expect(fs.existsSync(activePath)).toBe(true);
	});

	it('deletes rejected proposals', async () => {
		writeProposal(dir, 'test-rejected', PROPOSAL_CONTENT);
		const delegate = async () => 'REJECT';
		const result = await autoApplyProposals(dir, delegate);
		expect(result.rejected).toContain('test-rejected');

		const proposalPath = path.join(
			dir,
			'.swarm',
			'skills',
			'proposals',
			'test-rejected.md',
		);
		expect(fs.existsSync(proposalPath)).toBe(false);
	});

	it('skips proposals whose slug already exists as active', async () => {
		writeProposal(dir, 'already-active', PROPOSAL_CONTENT);
		writeActiveSkill(dir, 'already-active');

		const delegate = async () => 'APPROVE';
		const result = await autoApplyProposals(dir, delegate);
		expect(result.skipped).toContain('already-active');
		expect(result.approved).toHaveLength(0);
	});

	it('handles delegate errors gracefully', async () => {
		writeProposal(dir, 'test-error', PROPOSAL_CONTENT);
		const delegate = async () => {
			throw new Error('LLM unavailable');
		};
		const result = await autoApplyProposals(dir, delegate);
		expect(result.skipped).toContain('test-error');
	});

	it('skips (and does NOT delete) proposals on an ambiguous verdict', async () => {
		// Only an explicit REJECT may delete. A non-APPROVE/non-REJECT verdict
		// must leave the proposal in place for a future retry — never silent loss.
		writeProposal(dir, 'test-ambiguous', PROPOSAL_CONTENT);
		const delegate = async () => 'MAYBE — I am not certain about this one';
		const result = await autoApplyProposals(dir, delegate);
		expect(result.skipped).toContain('test-ambiguous');
		expect(result.approved).not.toContain('test-ambiguous');
		expect(result.rejected).not.toContain('test-ambiguous');
		const proposalPath = path.join(
			dir,
			'.swarm',
			'skills',
			'proposals',
			'test-ambiguous.md',
		);
		expect(fs.existsSync(proposalPath)).toBe(true);
	});

	it('respects batch limit', async () => {
		for (let i = 0; i < 8; i++) {
			writeProposal(dir, `batch-${i}`, PROPOSAL_CONTENT);
		}

		const delegate = async () => 'APPROVE';
		const result = await autoApplyProposals(dir, delegate);
		expect(result.approved.length).toBeLessThanOrEqual(5);
	});
});
