/**
 * Tests for the knowledge-to-skill compiler.
 */

import { afterEach, beforeEach, describe, expect, it, mock } from 'bun:test';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { resolveSwarmKnowledgePath } from '../../../src/hooks/knowledge-store';
import type { SwarmKnowledgeEntry } from '../../../src/hooks/knowledge-types';
import {
	activateProposal,
	clusterEntries,
	generateSkills,
	inspectSkill,
	isValidSlug,
	listSkills,
	renderSkillMarkdown,
	sanitizeSlug,
	selectCandidateEntries,
} from '../../../src/services/skill-generator';

let tmp: string;
beforeEach(() => {
	mock.restore();
	tmp = mkdtempSync(path.join(tmpdir(), 'swarm-skill-gen-'));
});
afterEach(() => {
	rmSync(tmp, { recursive: true, force: true });
	mock.restore();
});

function makeEntry(
	id: string,
	overrides: Partial<SwarmKnowledgeEntry> = {},
): SwarmKnowledgeEntry {
	return {
		id,
		tier: 'swarm',
		lesson: 'always declare scope before coder delegation',
		category: 'process',
		tags: ['scope'],
		scope: 'global',
		confidence: 0.9,
		status: 'established',
		confirmed_by: [
			{
				phase_number: 1,
				confirmed_at: new Date().toISOString(),
				project_name: 'test',
			},
			{
				phase_number: 2,
				confirmed_at: new Date().toISOString(),
				project_name: 'test',
			},
		],
		retrieval_outcomes: {
			applied_count: 0,
			succeeded_after_count: 0,
			failed_after_count: 0,
		},
		schema_version: 2,
		created_at: new Date().toISOString(),
		updated_at: new Date().toISOString(),
		project_name: 'test',
		triggers: ['coder delegation'],
		required_actions: ['call declare_scope'],
		forbidden_actions: ['heredoc bash writes'],
		applies_to_agents: ['coder'],
		directive_priority: 'critical',
		...overrides,
	};
}

async function seed(entries: SwarmKnowledgeEntry[]): Promise<void> {
	const dir = path.join(tmp, '.swarm');
	await mkdir(dir, { recursive: true });
	const lines = entries.map((e) => JSON.stringify(e)).join('\n') + '\n';
	await writeFile(resolveSwarmKnowledgePath(tmp), lines, 'utf-8');
}

describe('sanitizeSlug', () => {
	it('rejects path traversal slugs after sanitization', () => {
		const sanitized = sanitizeSlug('../../etc/passwd');
		expect(isValidSlug(sanitized)).toBe(true); // mapped to safe form
		expect(sanitized).not.toContain('..');
		expect(sanitized).not.toContain('/');
	});
	it('lowercases and collapses non-alnum to hyphens', () => {
		expect(sanitizeSlug('Coder Scope!')).toBe('coder-scope');
	});
});

describe('selectCandidateEntries', () => {
	it('excludes archived, low-confidence, and already-compiled entries', async () => {
		await seed([
			makeEntry('e1'),
			makeEntry('e2', { status: 'archived' }),
			makeEntry('e3', { confidence: 0.4 }),
			makeEntry('e4', { generated_skill_slug: 'already-compiled' }),
			makeEntry('e5', { confirmed_by: [] }),
		]);
		const cands = await selectCandidateEntries(tmp, {
			minConfidence: 0.85,
			minConfirmations: 2,
		});
		expect(cands.map((e) => e.id).sort()).toEqual(['e1']);
	});

	it('includes repeated high-confidence entries', async () => {
		await seed([
			makeEntry('a1'),
			makeEntry('a2', { lesson: 'declare scope before delegation, again' }),
		]);
		const cands = await selectCandidateEntries(tmp, {
			minConfidence: 0.85,
			minConfirmations: 2,
		});
		expect(cands.length).toBe(2);
	});
});

describe('renderSkillMarkdown', () => {
	it('produces required sections and frontmatter', async () => {
		const cluster = clusterEntries([makeEntry('rk1'), makeEntry('rk2')])[0];
		const md = renderSkillMarkdown(cluster);
		expect(md).toContain('---');
		expect(md).toMatch(/^name:\s+/m);
		expect(md).toContain('generated_from_knowledge:');
		expect(md).toContain('## Trigger');
		expect(md).toContain('## Required Procedure');
		expect(md).toContain('## Forbidden Shortcuts');
		expect(md).toContain('## Delegation Template');
		expect(md).toContain('## Reviewer Checks');
		expect(md).toContain('## Source Knowledge IDs');
		expect(md).toContain('generated by opencode-swarm skill-generator');
	});
});

describe('generateSkills draft mode', () => {
	it('writes only under .swarm/skills/proposals', async () => {
		await seed([makeEntry('g1'), makeEntry('g2')]);
		const result = await generateSkills({
			directory: tmp,
			mode: 'draft',
		});
		expect(result.written.length).toBeGreaterThan(0);
		for (const w of result.written) {
			expect(w.path).toContain('.swarm/skills/proposals/');
			expect(w.path.endsWith('.md')).toBe(true);
			expect(existsSync(w.path)).toBe(true);
		}
	});
});

describe('generateSkills active mode', () => {
	it('writes under .opencode/skills/generated/<slug>/SKILL.md and stamps source entries', async () => {
		await seed([makeEntry('h1'), makeEntry('h2')]);
		const result = await generateSkills({
			directory: tmp,
			mode: 'active',
		});
		expect(result.written.length).toBeGreaterThan(0);
		for (const w of result.written) {
			expect(w.path).toContain('.opencode/skills/generated/');
			expect(w.path.endsWith('SKILL.md')).toBe(true);
		}
		const stamped = readFileSync(resolveSwarmKnowledgePath(tmp), 'utf-8')
			.trim()
			.split('\n')
			.map((l) => JSON.parse(l));
		expect(stamped[0].generated_skill_path).toContain(
			'.opencode/skills/generated/',
		);
		expect(stamped[0].generated_skill_slug).toBeTruthy();
	});

	it('does not overwrite a non-generator-stamped active SKILL.md without force', async () => {
		await seed([makeEntry('p1'), makeEntry('p2')]);
		const cluster = clusterEntries([makeEntry('p1'), makeEntry('p2')])[0];
		const targetDir = path.join(
			tmp,
			'.opencode',
			'skills',
			'generated',
			cluster.slug,
		);
		await mkdir(targetDir, { recursive: true });
		await writeFile(
			path.join(targetDir, 'SKILL.md'),
			'# manual content (no generator stamp)\n',
			'utf-8',
		);
		const result = await generateSkills({
			directory: tmp,
			mode: 'active',
			slug: cluster.slug,
		});
		// The cluster's manual SKILL.md should be preserved; result should record skip.
		expect(
			result.skipped.some((s) =>
				s.reason.includes('manually edited skill exists'),
			),
		).toBe(true);
		const onDisk = readFileSync(path.join(targetDir, 'SKILL.md'), 'utf-8');
		expect(onDisk).toContain('manual content');
	});
});

describe('listSkills + inspectSkill + activateProposal', () => {
	it('lists drafts/active and inspects content', async () => {
		await seed([makeEntry('l1'), makeEntry('l2')]);
		const draft = await generateSkills({ directory: tmp, mode: 'draft' });
		const list = await listSkills(tmp);
		expect(list.proposals.length).toBeGreaterThan(0);
		expect(list.active.length).toBe(0);
		const slug = draft.written[0].slug;
		const inspect = await inspectSkill(tmp, slug);
		expect(inspect.found).toBe(true);
		expect(inspect.content).toContain('## Required Procedure');

		const activate = await activateProposal(tmp, slug);
		expect(activate.activated).toBe(true);
		const list2 = await listSkills(tmp);
		expect(list2.active.length).toBe(1);
	});
});
