/**
 * Tests for stale-active-skill reconciliation + detection blind spot
 * (issue #1477, Part C). Uses real temp directories and the real
 * regenerate/retire/listSkills paths against an empty knowledge store.
 */

import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import { existsSync, mkdtempSync, rmSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import {
	_internals,
	reconcileStaleActiveSkills,
} from '../../../src/services/skill-improver';

let tmp: string;
beforeEach(() => {
	tmp = mkdtempSync(path.join(tmpdir(), 'swarm-reconcile-'));
});
afterEach(() => {
	rmSync(tmp, { recursive: true, force: true });
});

async function writeActiveSkill(slug: string, content: string): Promise<string> {
	const dir = path.join(tmp, '.opencode', 'skills', 'generated', slug);
	await mkdir(dir, { recursive: true });
	const file = path.join(dir, 'SKILL.md');
	await writeFile(file, content, 'utf-8');
	return file;
}

function retiredMarkerPath(slug: string): string {
	return path.join(
		tmp,
		'.opencode',
		'skills',
		'generated',
		slug,
		'retired.marker',
	);
}

const SHIM = `---
name: my-shim
description: legacy shim
skill_origin: shim
---

# Shim
`;

const HEALTHY = `---
name: healthy
description: a healthy generated skill
source_knowledge_ids:
  - abc12345
generated_at: 2026-01-01T00:00:00.000Z
status: active
version: 1
skill_origin: generated
---

<!-- generated by opencode-swarm skill-generator. -->
# Healthy
`;

const UNPARSEABLE = `# Orphan Skill

No YAML frontmatter at all — the historical detection blind spot silently
skipped this file so it was never flagged or reconciled.
`;

describe('reconcileStaleActiveSkills (issue #1477)', () => {
	it('skips hand-authored shims (skill_origin: shim) without retiring them', async () => {
		await writeActiveSkill('my-shim', SHIM);

		const result = await reconcileStaleActiveSkills(tmp);

		expect(result.skipped).toContain('my-shim');
		expect(result.retired).not.toContain('my-shim');
		expect(result.regenerated).not.toContain('my-shim');
		// The shim file is untouched.
		expect(existsSync(retiredMarkerPath('my-shim'))).toBe(false);
	});

	it('leaves a healthy skill (parseable frontmatter + source ids) untouched', async () => {
		await writeActiveSkill('healthy', HEALTHY);

		const result = await reconcileStaleActiveSkills(tmp);

		expect(result.checked).toBe(0);
		expect(result.regenerated).not.toContain('healthy');
		expect(result.retired).not.toContain('healthy');
		expect(existsSync(retiredMarkerPath('healthy'))).toBe(false);
	});

	it('retires a stale skill that has no parseable frontmatter and no re-derivable source', async () => {
		await writeActiveSkill('orphan-xyz', UNPARSEABLE);

		// Empty knowledge store → regenerateSkill cannot re-derive → terminal retire.
		const result = await reconcileStaleActiveSkills(tmp);

		expect(result.checked).toBe(1);
		expect(result.retired).toContain('orphan-xyz');
		expect(existsSync(retiredMarkerPath('orphan-xyz'))).toBe(true);
	});

	it('dry run reports stale skills as retire-candidates without mutating them', async () => {
		await writeActiveSkill('orphan-xyz', UNPARSEABLE);

		const result = await reconcileStaleActiveSkills(tmp, { dryRun: true });

		expect(result.checked).toBe(1);
		expect(result.retired).toContain('orphan-xyz');
		// dry run must NOT create a retired marker.
		expect(existsSync(retiredMarkerPath('orphan-xyz'))).toBe(false);
	});

	it('returns an empty result when there are no active skills', async () => {
		const result = await reconcileStaleActiveSkills(tmp);
		expect(result).toEqual({
			regenerated: [],
			retired: [],
			skipped: [],
			checked: 0,
		});
	});
});

describe('gatherInventory detection blind spot (issue #1477)', () => {
	it('surfaces a frontmatter-less active skill as unparseable_frontmatter', async () => {
		await writeActiveSkill('orphan-xyz', UNPARSEABLE);

		const inv = await _internals.gatherInventory(tmp);

		const orphan = inv.staleActiveSkills.find((s) => s.slug === 'orphan-xyz');
		expect(orphan).toBeDefined();
		expect(orphan?.reasons).toContain('unparseable_frontmatter');
	});

	it('does NOT flag a shim-marked skill as stale', async () => {
		await writeActiveSkill('my-shim', SHIM);

		const inv = await _internals.gatherInventory(tmp);

		expect(inv.staleActiveSkills.find((s) => s.slug === 'my-shim')).toBeUndefined();
	});
});
