/**
 * Tests for the skill-reviser service.
 *
 * Covers: getSkillVersion, buildDeterministicRevision, reviseSkill (deterministic
 * and LLM paths), quota gating, promoted-skill detection, and exported constants.
 */

import { afterEach, beforeEach, describe, expect, it, mock } from 'bun:test';
import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import type {
	ReviseSkillParams,
	ViolationContext,
} from '../../../src/services/skill-reviser';
import {
	_internals,
	buildDeterministicRevision,
	getSkillVersion,
	MAX_REVISION_CALLS_PER_PHASE,
	REVISION_VIOLATION_THRESHOLD,
	reviseSkill,
} from '../../../src/services/skill-reviser';

let tmp: string;

beforeEach(() => {
	mock.restore();
	tmp = mkdtempSync(path.join(os.tmpdir(), 'swarm-reviser-'));
});

afterEach(() => {
	rmSync(tmp, { recursive: true, force: true });
	mock.restore();
});

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

const SAMPLE_SKILL = `---
name: test-skill
description: Test skill for testing
generated_from_knowledge:
  - k1
source_knowledge_ids:
  - k1
generated_at: 2026-06-01T00:00:00.000Z
confidence: 0.90
status: active
version: 1
skill_origin: generated
---

<!-- generated by opencode-swarm skill-generator. Do not edit by hand; edits will be preserved on regeneration only with controlled update mode. -->

# Test skill for testing

## Trigger

- When writing tests

## Required Procedure

- Always use bun:test
- Write assertions for edge cases

## Forbidden Shortcuts

- Do not use jest or vitest

## Delegation Template

When delegating a task affected by this skill, include:

\`\`\`
SKILLS: file:.opencode/skills/generated/test-skill/SKILL.md
\`\`\`

## Reviewer Checks

- Verify each required action above appears in the diff.

## Source Knowledge IDs

- k1 — Always use bun:test for testing
`;

function makeViolation(
	overrides: Partial<ViolationContext> = {},
): ViolationContext {
	return {
		taskId: 'task-001',
		agent: 'coder',
		verdict: 'violated',
		reviewerNotes: 'Used jest instead of bun:test',
		timestamp: '2026-06-10T12:00:00.000Z',
		...overrides,
	};
}

function writeSkillFile(content: string): string {
	const skillDir = path.join(
		tmp,
		'.opencode',
		'skills',
		'generated',
		'test-skill',
	);
	mkdirSync(skillDir, { recursive: true });
	const skillPath = path.join(skillDir, 'SKILL.md');
	writeFileSync(skillPath, content, 'utf-8');
	return skillPath;
}

function ensureSwarmDir(): void {
	mkdirSync(path.join(tmp, '.swarm', 'skill-changelogs'), { recursive: true });
}

// ---------------------------------------------------------------------------
// getSkillVersion
// ---------------------------------------------------------------------------

describe('getSkillVersion', () => {
	it('reads version from frontmatter and returns the correct number', async () => {
		const skillPath = writeSkillFile(SAMPLE_SKILL);
		const version = await getSkillVersion(skillPath);
		expect(version).toBe(1);
	});

	it('returns 1 when the version field is missing from frontmatter', async () => {
		const noVersionContent = SAMPLE_SKILL.replace(/^version:\s*\d+\s*$/m, '');
		const skillPath = writeSkillFile(noVersionContent);
		const version = await getSkillVersion(skillPath);
		expect(version).toBe(1);
	});

	it('returns 1 when the file does not exist', async () => {
		const version = await getSkillVersion(
			path.join(tmp, 'nonexistent', 'SKILL.md'),
		);
		expect(version).toBe(1);
	});
});

// ---------------------------------------------------------------------------
// buildDeterministicRevision
// ---------------------------------------------------------------------------

describe('buildDeterministicRevision', () => {
	it('inserts a Revision Notes section before Source Knowledge IDs', () => {
		const violations = [makeViolation()];
		const result = _internals.buildDeterministicRevision(
			SAMPLE_SKILL,
			1,
			violations,
		);

		const revisionIdx = result.indexOf('## Revision Notes');
		const sourceIdx = result.indexOf('## Source Knowledge IDs');

		expect(revisionIdx).toBeGreaterThan(-1);
		expect(sourceIdx).toBeGreaterThan(-1);
		expect(revisionIdx).toBeLessThan(sourceIdx);
	});

	it('updates the version in frontmatter from 1 to 2', () => {
		const violations = [makeViolation()];
		const result = _internals.buildDeterministicRevision(
			SAMPLE_SKILL,
			1,
			violations,
		);

		const versionMatch = result.match(/^version:\s*(\d+)\s*$/m);
		expect(versionMatch).not.toBeNull();
		expect(versionMatch![1]).toBe('2');
	});

	it('replaces prior Revision Notes on a second revision', () => {
		const violations = [makeViolation()];
		// First revision: version 1 -> 2
		const firstRevision = _internals.buildDeterministicRevision(
			SAMPLE_SKILL,
			1,
			violations,
		);

		// Second revision: version 2 -> 3
		const secondViolation = makeViolation({
			taskId: 'task-002',
			reviewerNotes: 'Still using jest',
		});
		const secondRevision = _internals.buildDeterministicRevision(
			firstRevision,
			2,
			[secondViolation],
		);

		// Only one Revision Notes section should exist
		const revisionNotesCount = (
			secondRevision.match(/## Revision Notes/g) || []
		).length;
		expect(revisionNotesCount).toBe(1);

		// Should reference version 3 in the revision notes
		expect(secondRevision).toContain('### Version 3');
		// Should NOT contain the old version 2 revision header
		expect(secondRevision).not.toContain('### Version 2');

		// Frontmatter should say version 3
		const versionMatch = secondRevision.match(/^version:\s*(\d+)\s*$/m);
		expect(versionMatch![1]).toBe('3');
	});

	it('preserves all other sections intact', () => {
		const violations = [makeViolation()];
		const result = _internals.buildDeterministicRevision(
			SAMPLE_SKILL,
			1,
			violations,
		);

		// All standard sections must be present
		const requiredSections = [
			'## Trigger',
			'## Required Procedure',
			'## Forbidden Shortcuts',
			'## Delegation Template',
			'## Reviewer Checks',
			'## Source Knowledge IDs',
		];
		for (const section of requiredSections) {
			expect(result).toContain(section);
		}

		// Original content in those sections should remain
		expect(result).toContain('Always use bun:test');
		expect(result).toContain('Do not use jest or vitest');
		expect(result).toContain('When writing tests');
	});
});

// ---------------------------------------------------------------------------
// reviseSkill — deterministic (no delegate)
// ---------------------------------------------------------------------------

describe('reviseSkill — deterministic (no delegate)', () => {
	it('returns { revised: false, reason: "no_violations" } when there are no violations', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		const result = await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
		});

		expect(result.revised).toBe(false);
		expect(result.reason).toBe('no_violations');
	});

	it('produces a deterministic revision and writes it to disk when violations are present and no delegate is provided', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		const result = await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
			now: new Date('2026-06-10T12:00:00.000Z'),
		});

		expect(result.revised).toBe(true);
		expect(result.reason).toBe('deterministic_revision');
		expect(result.quotaConsumed).toBe(false);
	});

	it('writes the revised file with version 2 in frontmatter', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		const result = await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
			now: new Date('2026-06-10T12:00:00.000Z'),
		});

		expect(result.newVersion).toBe(2);

		const written = readFileSync(skillPath, 'utf-8');
		const versionMatch = written.match(/^version:\s*(\d+)\s*$/m);
		expect(versionMatch).not.toBeNull();
		expect(versionMatch![1]).toBe('2');
	});

	it('appends a changelog entry after deterministic revision', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
			now: new Date('2026-06-10T12:00:00.000Z'),
		});

		const changelogPath = path.join(
			tmp,
			'.swarm',
			'skill-changelogs',
			'test-skill.jsonl',
		);
		expect(existsSync(changelogPath)).toBe(true);

		const changelogContent = readFileSync(changelogPath, 'utf-8').trim();
		const entry = JSON.parse(changelogContent);
		expect(entry.version).toBe(2);
		expect(entry.action).toBe('revised');
		expect(entry.reason).toBe('deterministic_revision');
	});

	it('rejects deterministic revision that does not strictly improve evals before writing', async () => {
		ensureSwarmDir();
		const currentContent = `${SAMPLE_SKILL}\nlegacy sentinel requirement\n`;
		const skillPath = writeSkillFile(currentContent);
		const evalDir = path.join(tmp, '.swarm', 'skills', 'evals', 'test-skill');
		mkdirSync(evalDir, { recursive: true });
		writeFileSync(
			path.join(evalDir, 'cases.json'),
			JSON.stringify({ required_phrases: ['legacy sentinel requirement'] }),
			'utf-8',
		);

		const result = await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent,
			currentVersion: 1,
		});

		expect(result.revised).toBe(false);
		expect(result.reason).toContain('validation_failed');
		expect(readFileSync(skillPath, 'utf-8')).toBe(currentContent);
		expect(
			existsSync(
				path.join(tmp, '.swarm', 'skill-changelogs', 'test-skill.jsonl'),
			),
		).toBe(false);
		expect(
			existsSync(path.join(tmp, '.swarm', 'skills', 'rejected-edits.jsonl')),
		).toBe(true);
	});

	it('preserves all required sections in the revised file', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
			now: new Date('2026-06-10T12:00:00.000Z'),
		});

		const written = readFileSync(skillPath, 'utf-8');
		const requiredSections = [
			'## Trigger',
			'## Required Procedure',
			'## Forbidden Shortcuts',
			'## Delegation Template',
			'## Reviewer Checks',
			'## Source Knowledge IDs',
		];
		for (const section of requiredSections) {
			expect(written).toContain(section);
		}
	});
});

// ---------------------------------------------------------------------------
// reviseSkill — LLM path
// ---------------------------------------------------------------------------

describe('reviseSkill — LLM path', () => {
	it('succeeds when the delegate returns valid revised content', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		const validLLMOutput = `---
name: test-skill
description: Test skill for testing
generated_from_knowledge:
  - k1
source_knowledge_ids:
  - k1
generated_at: 2026-06-01T00:00:00.000Z
confidence: 0.90
status: active
version: 2
skill_origin: generated
---

# Test skill for testing

## Trigger

- When writing tests

## Required Procedure

- Always use bun:test (never jest or vitest)
- Write assertions for edge cases
- Include negative test cases

## Forbidden Shortcuts

- Do not use jest or vitest
- Do not skip test assertions

## Delegation Template

When delegating a task affected by this skill, include:

\`\`\`
SKILLS: file:.opencode/skills/generated/test-skill/SKILL.md
\`\`\`

## Reviewer Checks

- Verify each required action above appears in the diff.

## Source Knowledge IDs

- k1 — Always use bun:test for testing
`;

		const mockDelegate = mock(
			async (_system: string, _user: string) => validLLMOutput,
		);

		// Pre-seed quota so reserveQuota succeeds
		const quotaDir = path.join(tmp, '.swarm');
		mkdirSync(quotaDir, { recursive: true });

		const result = await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
			delegate: mockDelegate,
			now: new Date('2026-06-10T12:00:00.000Z'),
		});

		expect(result.revised).toBe(true);
		expect(result.reason).toBe('llm_revision');
		expect(result.quotaConsumed).toBe(true);
		expect(result.newVersion).toBe(2);
		expect(mockDelegate).toHaveBeenCalledTimes(1);
	});

	it('returns { revised: false, reason: "llm_output_invalid" } when the delegate returns content without frontmatter', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		const invalidOutput = `# Test skill
This has no frontmatter at all.

## Required Procedure
- something

## Source Knowledge IDs
- k1
`;

		const mockDelegate = mock(
			async (_system: string, _user: string) => invalidOutput,
		);

		const quotaDir = path.join(tmp, '.swarm');
		mkdirSync(quotaDir, { recursive: true });

		const result = await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
			delegate: mockDelegate,
			now: new Date('2026-06-10T12:00:00.000Z'),
		});

		expect(result.revised).toBe(false);
		expect(result.reason).toBe('llm_output_invalid');
		expect(result.quotaConsumed).toBe(true);
	});
});

// ---------------------------------------------------------------------------
// Quota
// ---------------------------------------------------------------------------

describe('reviseSkill — quota', () => {
	it('returns { revised: false, reason: "quota_exhausted" } when quota is fully consumed', async () => {
		ensureSwarmDir();
		const skillPath = writeSkillFile(SAMPLE_SKILL);

		const mockDelegate = mock(
			async (_system: string, _user: string) => 'irrelevant',
		);

		// Pre-exhaust quota: write a state file showing all slots used
		const quotaDir = path.join(tmp, '.swarm');
		mkdirSync(quotaDir, { recursive: true });
		const today = new Date('2026-06-10T12:00:00.000Z')
			.toISOString()
			.slice(0, 10);
		writeFileSync(
			path.join(quotaDir, 'skill-improver-quota.json'),
			JSON.stringify({
				date: today,
				calls_used: 10,
				max_calls: 10,
				window: 'utc',
			}),
			'utf-8',
		);

		const result = await reviseSkill({
			directory: tmp,
			slug: 'test-skill',
			skillPath,
			violationContexts: [makeViolation()],
			currentContent: SAMPLE_SKILL,
			currentVersion: 1,
			delegate: mockDelegate,
			now: new Date('2026-06-10T12:00:00.000Z'),
		});

		expect(result.revised).toBe(false);
		expect(result.reason).toBe('quota_exhausted');
		expect(result.quotaConsumed).toBe(false);
		// The delegate should never have been called
		expect(mockDelegate).toHaveBeenCalledTimes(0);
	});
});

// ---------------------------------------------------------------------------
// Promoted skills
// ---------------------------------------------------------------------------

describe('promoted skill detection', () => {
	it('detects skill_origin: promoted_external via frontmatter parsing', () => {
		const promotedContent = SAMPLE_SKILL.replace(
			'skill_origin: generated',
			'skill_origin: promoted_external',
		);

		const match = promotedContent.match(/^skill_origin:\s*(.+)\s*$/m);
		expect(match).not.toBeNull();
		expect(match![1].trim()).toBe('promoted_external');
	});
});

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

describe('constants', () => {
	it('REVISION_VIOLATION_THRESHOLD is 0.15', () => {
		expect(REVISION_VIOLATION_THRESHOLD).toBe(0.15);
	});

	it('MAX_REVISION_CALLS_PER_PHASE is 3', () => {
		expect(MAX_REVISION_CALLS_PER_PHASE).toBe(3);
	});
});
